on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

name: Test-Services

jobs:
  Test-Services:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      EMODNETWFS_CI: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::XML
          needs: check

      - name: Test Services
        run: |
          options(crayon.enabled = TRUE)
          install.packages(".", repos = NULL, type="source")
          test_service <- lapply(emodnet.wfs::emodnet_wfs()$service_name, emodnet.wfs::emodnet_init_wfs_client);
          testthat::test_that("All services work", {testthat::expect_equal(class(test_service), "list")})
        shell: Rscript {0}
